# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctrlc < Formula
  desc "CLI for ctrlplane - A deployment orchestration tool"
  homepage "https://github.com/ctrlplanedev/cli"
  version "0.15.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ctrlplanedev/cli/releases/download/v0.15.2/ctrlc_Darwin_x86_64.tar.gz"
      sha256 "190a8f07698e6b9e9aaa4cbe2fcd041166852132832e9ec51349885aa820c17d"
    end
    on_arm do
      url "https://github.com/ctrlplanedev/cli/releases/download/v0.15.2/ctrlc_Darwin_arm64.tar.gz"
      sha256 "a3968b2dfbf3789044127b533cfefa8bca1231d37c9b069b49742296c7027f72"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctrlplanedev/cli/releases/download/v0.15.2/ctrlc_Linux_x86_64.tar.gz"
        sha256 "9a0b2bac9fc6d49de10e5de951116b89306024d826ba858f30d92167bfccf6d8"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctrlplanedev/cli/releases/download/v0.15.2/ctrlc_Linux_arm64.tar.gz"
        sha256 "27f7fdf29cb91d784f265125c980eae644d3f92ae42ee243b36d331e6b4512ad"
      end
    end
  end

  def install
    bin.install "ctrlc"
  end

  test do
    system "#{bin}/ctrlc", "version"
  end
end
